// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// ignore: depend_on_referenced_packages
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2R4Q5F-SRtfRiMgVvSrxqi4aWORcTE_o',
    appId: '1:599338824531:web:711a5ff79a0ee3a1a567a6',
    messagingSenderId: '599338824531',
    projectId: 'instagram-6da85',
    authDomain: 'instagram-6da85.firebaseapp.com',
    storageBucket: 'instagram-6da85.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdlZMXnjKe4oOH55mvvR8ICg-GiRiD2uk',
    appId: '1:599338824531:android:25cb397c3ee9ca26a567a6',
    messagingSenderId: '599338824531',
    projectId: 'instagram-6da85',
    storageBucket: 'instagram-6da85.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQPAkTALEvyNiaCqHqMO5JVO3kyE06Iq8',
    appId: '1:599338824531:ios:d6a326ec6c7ed662a567a6',
    messagingSenderId: '599338824531',
    projectId: 'instagram-6da85',
    storageBucket: 'instagram-6da85.appspot.com',
    iosClientId:
        '599338824531-ogvi6sftjtumnbf2291ci02baec04ktt.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQPAkTALEvyNiaCqHqMO5JVO3kyE06Iq8',
    appId: '1:599338824531:ios:d6a326ec6c7ed662a567a6',
    messagingSenderId: '599338824531',
    projectId: 'instagram-6da85',
    storageBucket: 'instagram-6da85.appspot.com',
    iosClientId:
        '599338824531-ogvi6sftjtumnbf2291ci02baec04ktt.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramApp',
  );
}
